
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-12
owner: ucsb-cs156-s25
repo_name: team01-s25-12
pull_requests: [{"author":{"id":"MDQ6VXNlcjc4NzczNjU1","is_bot":false,"login":"tizerk","name":"Jay Joo"},"headRefName":"jj-UCSBDiningCommonsMenuItem-delete-endpoint","number":53,"title":"jj - ucsb dining commons menu item delete endpoint","url":"https://github.com/ucsb-cs156-s25/team01-s25-12/pull/53"},{"author":{"id":"MDQ6VXNlcjc4NzczNjU1","is_bot":false,"login":"tizerk","name":"Jay Joo"},"headRefName":"jj-UCSBDiningCommonsMenuItem-put-endpoint","number":52,"title":"Jj ucsb dining commons menu item put endpoint","url":"https://github.com/ucsb-cs156-s25/team01-s25-12/pull/52"},{"author":{"id":"MDQ6VXNlcjc4NzczNjU1","is_bot":false,"login":"tizerk","name":"Jay Joo"},"headRefName":"jj-UCSBDiningCommonsMenuItem-get-endpoint","number":49,"title":"Jj ucsb dining commons menu item get endpoint","url":"https://github.com/ucsb-cs156-s25/team01-s25-12/pull/49"}]
