
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-12
owner: ucsb-cs156-s25
repo_name: team01-s25-12
pull_requests: [{"author":{"id":"MDQ6VXNlcjQwNDQzMzY4","is_bot":false,"login":"yxz29315","name":"Shawn Zhang"},"headRefName":"UCSBOrganization-delete","number":64,"title":"Add DELETE endpoint for a specific record in UCSBOrganization table.","url":"https://github.com/ucsb-cs156-s25/team01-s25-12/pull/64"},{"author":{"id":"MDQ6VXNlcjY3NTU5NDUy","is_bot":false,"login":"simony05","name":"Simon Yan"},"headRefName":"Simon-MenuItemReviewController","number":63,"title":"Simon menu item review controller","url":"https://github.com/ucsb-cs156-s25/team01-s25-12/pull/63"},{"author":{"id":"MDQ6VXNlcjQwNDQzMzY4","is_bot":false,"login":"yxz29315","name":"Shawn Zhang"},"headRefName":"UCSBOrganization-put","number":62,"title":"Add PUT (edit) endpoint for a single record in UCSBOrganization table","url":"https://github.com/ucsb-cs156-s25/team01-s25-12/pull/62"},{"author":{"id":"MDQ6VXNlcjQwNDQzMzY4","is_bot":false,"login":"yxz29315","name":"Shawn Zhang"},"headRefName":"UCSBOrganization-get","number":61,"title":"Add GET (show) endpoint for a single record in UCSBOrganization table","url":"https://github.com/ucsb-cs156-s25/team01-s25-12/pull/61"},{"author":{"id":"U_kgDOB7QARg","is_bot":false,"login":"mic-wu","name":""},"headRefName":"mw-helprequests-controller-delete","number":60,"title":"Mw helprequests controller delete","url":"https://github.com/ucsb-cs156-s25/team01-s25-12/pull/60"},{"author":{"id":"MDQ6VXNlcjQwNDQzMzY4","is_bot":false,"login":"yxz29315","name":"Shawn Zhang"},"headRefName":"UCSBOrganization-create-controller","number":59,"title":"Create UCSBOrganizationController, add GET (index) and POST (create)","url":"https://github.com/ucsb-cs156-s25/team01-s25-12/pull/59"},{"author":{"id":"MDQ6VXNlcjMwOTM2NDI2","is_bot":false,"login":"arthurwu17","name":"Arthur Wu"},"headRefName":"aw-articles-controller-delete","number":57,"title":"Aw articles controller delete","url":"https://github.com/ucsb-cs156-s25/team01-s25-12/pull/57"}]
