
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-12
owner: ucsb-cs156-s25
repo_name: team01-s25-12
pull_requests: [{"author":{"id":"U_kgDOB7QARg","is_bot":false,"login":"mic-wu","name":""},"headRefName":"mw-create-db-table-helprequests","number":47,"title":"Create database table for HelpRequests","url":"https://github.com/ucsb-cs156-s25/team01-s25-12/pull/47"},{"author":{"id":"MDQ6VXNlcjMwOTM2NDI2","is_bot":false,"login":"arthurwu17","name":"Arthur Wu"},"headRefName":"Arthur-Articles","number":44,"title":"Create database tables for Articles","url":"https://github.com/ucsb-cs156-s25/team01-s25-12/pull/44"},{"author":{"id":"MDQ6VXNlcjY3NTU5NDUy","is_bot":false,"login":"simony05","name":"Simon Yan"},"headRefName":"Simon-MenuItemReviews","number":43,"title":"Create database table for MenuItemReviews","url":"https://github.com/ucsb-cs156-s25/team01-s25-12/pull/43"}]
