
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-12
owner: ucsb-cs156-s25
repo_name: team01-s25-12
pull_requests: [{"author":{"id":"MDQ6VXNlcjQwNDQzMzY4","is_bot":false,"login":"yxz29315","name":"Shawn Zhang"},"headRefName":"UCSBOrganization-put","number":62,"title":"Add PUT (edit) endpoint for a single record in UCSBOrganization table","url":"https://github.com/ucsb-cs156-s25/team01-s25-12/pull/62"},{"author":{"id":"MDQ6VXNlcjQwNDQzMzY4","is_bot":false,"login":"yxz29315","name":"Shawn Zhang"},"headRefName":"UCSBOrganization-get","number":61,"title":"Add GET (show) endpoint for a single record in UCSBOrganization table","url":"https://github.com/ucsb-cs156-s25/team01-s25-12/pull/61"}]
